name: arpav-ppcv

services:

  webapp:
    image: "ghcr.io/geobeyond/arpav-ppcv-backend/arpav-ppcv-backend:${CURRENT_GIT_BRANCH:-latest}"
    environment:
      ARPAV_PPCV__DEBUG: true
      ARPAV_PPCV__BIND_HOST: 0.0.0.0
      ARPAV_PPCV__BIND_PORT: 5001
      ARPAV_PPCV__PUBLIC_URL: http://localhost:5001
      ARPAV_PPCV__UVICORN_LOG_CONFIG_FILE: /home/appuser/app/dev-log-config.yml
      ARPAV_PPCV__DJANGO_APP__THREDDS__PORT: 8081
      ARPAV_PPCV__DJANGO_APP__DB_DSN: postgres://postgres:postgres@db:5432/postgres
      ARPAV_PPCV__DJANGO_APP__REDIS_DSN: redis://redis:6379
      ARPAV_PPCV__DJANGO_APP__SECRET_KEY: some-dev-key
    ports:
      - target: 5001
        published: 5001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: $PWD
        target: /home/appuser/app

  db:
    image: mdillon/postgis:10
    environment:
      POSTGRES_USER: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      timeout: 3s
      start_period: 1m
      retries: 10
      test: |
        export PGPASSWORD=$${POSTGRES_PASSWORD:-}
        args="--host 127.0.0.1 --username $${POSTGRES_USER} --dbname $${POSTGRES_DB} --quiet --no-align --tuples-only"
        response=$$(echo 'SELECT 1' | psql $${args})
        if [ $${response} = '1' ];
        then exit 0;
        else echo "+++++++++++++DB $${POSTGRES_DB} is not up+++++++++++++"; exit 1;
        fi

  redis:
    image: redis:4
    restart: unless-stopped

  martin:
    image: 'maplibre/martin:v0.6'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${PGPASSWORD}@postgis/${POSTGRES_DB_NAME}
      RUST_LOG: actix_web=info,martin=debug,tokio_postgres=debug
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: