version: '3'
services:

  postgis:
    image: mdillon/postgis:10
    container_name: arpav_postgis
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      PGPASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB_NAME}'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: arpav_redis
    image: redis:4
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redisdata:/data

  backend:
    env_file: .env
    container_name: backend.api
    image: "ghcr.io/geobeyond/arpav-ppcv-backend/arpav-ppcv-backend:${CURRENT_GIT_BRANCH:-latest}"
    restart: unless-stopped
    environment:
      GUNICORN_WORKERS: 15
      GUNICORN_WORKER_TIMEOUT: 120
#    ports:
#      - 8000:8000
    depends_on:
      - postgis
    volumes:
      - type: bind
        source: $PWD
        target: /home/appuser/app

  martin:
    image: 'maplibre/martin:v0.6'
    container_name: martin
    restart: unless-stopped
    expose:
      - 3000
#    ports:
#      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${PGPASSWORD}@postgis/${POSTGRES_DB_NAME}
      - RUST_LOG=actix_web=info,martin=debug,tokio_postgres=debug
    depends_on:
      - postgis

  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${SSL_CERTIFICATE}:/etc/ssl/cert.crt
      - ${SSL_KEY}:/etc/ssl/private/cert.key
    expose:
      - 80
      - 443
    ports:
      - 8000:80
      - 4430:443
    environment:
     - NGINX_HOST=proxy
     - NGINX_PORT=8000
    depends_on:
      - backend
      - thredds
      - martin

  thredds:
    container_name: thredds
    build:
      context: ./thredds_helper
#    ports:
#     - "8089:8089"
    expose:
      - 8089
    restart: always
    environment:
     - THREDDS_PASSWORD=${THREDDS_PASSWORD}

#  frontend:
#    container_name: frontend
#    image: ppcv_frontend:latest
#    build:
#      context: ./Arpav-PPCV
#    expose:
#      - 80
#    restart: always

volumes:
  redisdata:
  pgdata: