version: "3"

services:
#    tileserver:
#        container_name: tileserver
#        image: klokantech/tileserver-gl:v2.5.0
#        restart: always
#        ports:
#            - 80:80
#    #    env_file: .env
#        volumes:
#            - ./data:/data
##            - ./data/fonts:/fonts
##            - ./data/styles:/styles
#        environment:
#            NODE_ENV: 'development'
#
#    maputnik:
#        container_name: maputnik
#        image: maputnik/editor
#        restart: always
#        ports:
#            - 8888:8888
#        environment:
#            NODE_ENV: 'development'


#cd /data;
#apt update;apt-get install --no-install-recommends -y libvips libvips-dev pip libtiff5 optipng pngquant;pip install gdal2mbtiles;
#gdal_merge.py -o gebco.tif gebco_2022_n*.tif;
#gdalwarp  -t_srs EPSG:3857 -r near -of GTiff gebco.tif gebco.3857.tif;
##for f in *.tif; do echo "Processing $f file..."; gdal_translate -of mbtiles $f $f.mbtiles; done;
###gdal_translate -of mbtiles gebco.3857.tif gebco.mbtiles
##gdal2mbtiles -v --name bathymetry --min-resolution 1 --max-resolution 14  gebco.3857.tif  gebco.mbtiles
##gdal2mbtiles -v --name bathymetry --min-resolution 1 --max-resolution 14  gebco.tif  gebco.mbtiles
##gdal_translate -of mbtiles gebco.tif  gebco.mbtiles

    gdal:
        container_name: gdal
        image: bjreppen/gdal-mbtiles
        restart: always
        volumes:
            - ./gebco:/data
        environment:
            NODE_ENV: 'development'
        command: "sleep 36000"



    mbtileserver:
        image: consbio/mbtileserver:latest
        container_name: mbtileserver
        entrypoint: /mbtileserver --enable-reload-signal
        restart: always
        ports:
            - 8002:8000
        volumes:
            - ./gebco:/tilesets

    maputnik:
        container_name: maputnik
        image: maputnik/editor
        restart: always
        ports:
            - 8888:8888
        environment:
            NODE_ENV: 'development'